version: "3.8"

services:
  ip-telegram-bot:
    container_name: main_app
    depends_on:
      - database
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crud
      - PORT=8080

  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
