version: "3.8"

services:
  server:
    container_name: server
    depends_on:
      - database
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crud
      - PORT=8080

  bot:
    container_name: bot
    depends_on:
      - database
    build:
      context: .
      dockerfile: bot.Dockerfile
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crud

  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
